[template]
name = "Example Project"
authors = ["Quarent <topfyf@qq.com>"]

[meta]
name = "Tex Jam"
slug = "(((name.lower().replace(' ', '-'))))"
age_of_father = 50
age_of_mother = { type = "int", "default" = "(((age_of_father - 2)))" }
have_brother = false
sister_name = { type = "str", choices = ["Alice", "Bob", "Cathy"] }
